makemigrations:
	python manage.py makemigrations

migrate:
	python manage.py migrate

runserver:
	python manage.py runserver

superuser:
	python manage.py createsuperuser

shell:
	python manage.py shell

test:
	python manage.py test main.tests.tournament